on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup_python@main
          with:
              python-version: '3.x'
        - uses: actions/setup_node@main
          with:
              node-version: '15.x'
        - run: |
              python extendedUnicode.py
              node exentendedUnicode.js
