on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - uses: actions/setup-node@main
          with:
              node-version: '15.x'
        - uses: actions/setup-java@main
          with:
              java-version: 15
        - run: |
              python extendedUnicode.py
              node extendedUnicode.js
              java extendedUnicode.java
    cpp:
        runs-on: ubuntu-latest
        container: gcc
        steps:
        - uses: actions/checkout@main
        - run: |
              g++ -std=c++2b -O2 -march=native extendedUnicode.cpp
              ./a.out  
